### ISSUE TITLE
isUpgradeAvailable bug

### ISSUE THREAD

**Issue by kal27** [aritraroy/RxMagneto#1]
Hello there,
First of all I quite like the library, while doing some testing I have found that isUpgradeAvailable is returning true even though the version name of the installed app and the one on the playstore is the same.
To be extra sure I even checked the updates page in google play store(Open playstore -> Side menu -> My apps & games) and confirmed that there were no updates available for that app.

After through all the apps with package manager the method returned true for all of them for some reason. 

Thanks

**Comment by aritraroy** [comment]
This is weird. I have tested it thoroughly and never found this issue. Can you tell me for which package are you specifically seeing this bug?

**Comment by mIbrahim017** [comment]
After checking the code , the code checking for the version name and some time the store has this name "Varies with device" so even you have the last version the condition will true

**Comment by kal27** [comment]
Yes I think that is the problem I have had

**Comment by AggarwalAnkit** [comment]
Hey, @aritraroy I was looking for some way to check the latest app version on play store for a particular package name and found this library :). In isUpgradeAvailable(packageName) function you are verifying the version name of the current app with the version name we get from play store for the given package. But check should be made on the basis of package name passed to that function. Also, before checking app version on play store there can be a check whether app is present in the device or not. Otherwise, it will always return true. Also, did you find any way to get latest app version even if playstore shows "Varies with device"?

**Comment by aritraroy** [comment]
1) Thanks for the bug. I have missed that. Will fix the checking from the current package to the specified package by the user.

2) Yes, you are right. It should be checked if the package is present in the device or not. I will update that soon.

3) There is no way to find the version if Play Store gives "Varies with device" string. But I will handle that appropriately, but the actual version can still not be retrieved.

Thanks for your suggestions. If you want you can fix these and send me a PR or I will do it very soon. :-)

**Comment by AggarwalAnkit** [comment]
Have sent the PR for above

**Comment by aritraroy** [comment]
Thank you for your PR. I have merged it. Will soon release an update after some testing.
